### ISSUE TITLE
Encryption?

### ISSUE THREAD

**Issue by findchris** [Graylog2/gelf-rb#17]
Currently, we're using EC2 for our app servers and gralog2 server, and unlike syslog, GELF seems to lack security, leaving us reluctant to use it.  Any plans for security/encryption of GELF log messages?  

Cheers.

**Comment by tubesenf** [comment]
Any progress on encryption? Included in Version 1.1 ?

**Comment by phlegx** [comment]
I also wanted to bump this. Is there encryption out pf the box available now? i.e. GELF HTTPS

thanks!

**Comment by milgner** [comment]
Duplicate of #37. Also note that there was a PR (#39) a while back, which unfortunately has not yet been merged to `master`.

**Comment by kaiomagalhaes** [comment]
Any ideas about when we will have the ssl feature?

**Comment by milgner** [comment]
@kaiomagalhaes I just opened #45 with a new implementation of this. It works for me but it would be great to get additional feedback from someone else, too :)

**Comment by milgner** [comment]
I'm proud to announce that I just pushed a new version which supports TLS on TCP connections. We'll shortly release the gem version 3.0, until then you can point your Gemfile to Github. Feedback welcome!
