### ISSUE TITLE
Getting ArgumentError

### ISSUE THREAD

**Issue by gavinheale** [Graylog2/gelf-rb#24]
Hi,

I am new to Graylog2 and I have just tried to get my first rails application integrated.  All I have done is add the line:

config.logger = GELF::Logger.new("192.168.20.51", 12201, "WAN", { :facility => "testapp" })

to my development.rb.  

This seems to work ok, in that I am getting messages through to Graylog2 but I also get a lot of:

ArgumentError: short_message is missing. Options version, short_message and host must be set.

I think these are just blank lines but cannot be sure.  I see that there was a pull request to fix blank lines but it was never merged.  Could that be the problem?

Regards,
Gavin

**Comment by milgner** [comment]
My recommendation would be to use a gem like [lograge](https://github.com/roidrage/lograge) to convert the Rails logs to a format better suited to structured logging. From the point of the logging code, receiving empty log messages is a bit silly and not that surprising that it complains.
