### ISSUE TITLE
GELF in rails seems to ignore log levels completely

### ISSUE THREAD

**Issue by gravis** [Graylog2/gelf-rb#25]
Hi,

it seems gelf is not relying on rails log levels at all:

```ruby
  app_name = config.action_mailer.default_url_options.try(:fetch, :host) || Rails.application.class.name.underscore.split('/').tap{|i|i.pop}.join('/')
  config.logger = GELF::Logger.new("172.31.XX.XX", 1515, "LAN", {:host => app_name, :environment => Rails.env, :facility => "rails" })
```

We have all the message from the DEBUG level in graylog.
We're tried to add a :level option:

```ruby
  config.logger = GELF::Logger.new("172.31.XX.XX", 1515, "LAN", {:host => app_name, :environment => Rails.env, :facility => "rails", :level => GELF::INFO })
```

we have also added:

```
config.log_level = :info
```

with no success.
Any idea why this isn't working as expected?
We're using latest version of gelf gem (1.4.0)

Thanks

**Comment by milgner** [comment]
The options hash usually takes string arguments. Specifying 'level' is the correct way. I'll close the ticket since it seems to have been resolved.
