### ISSUE TITLE
Transmission over TCP/HTTP/SSL protocols

### ISSUE THREAD

**Issue by mariusgrigaitis** [Graylog2/gelf-rb#37]
If I'm not mistaken currently this library supports sending events only over UDP.

I'm missing sending events over TCP, HTTP, TCP+SSL. 

Are there any plans for that?

**Comment by siawyoung** [comment]
I need this functionality as well. I'll be forking and working on a TCPSender - will let you know if I manage to get it out.

**Comment by rikatz** [comment]
:+1: 

Was trying to implement this on the library, but have poor abilities with ruby :(

**Comment by siawyoung** [comment]
My fork of gelf-rb includes TCP support: https://github.com/siawyoung/gelf-rb

**Comment by rikatz** [comment]
@siawyoung Nice :) Couldn't you open a Merge Request to the main project? Logstash references this library, so it would start working on the newly logstash releases :)

Thanks!

**Comment by milgner** [comment]
Also see #39.

**Comment by milgner** [comment]
I'm proud to announce that I just pushed a new version which supports TLS on TCP connections. We'll shortly release the gem version 3.0, until then you can point your Gemfile to Github. Feedback welcome!
