### ISSUE TITLE
Long log message crashes Graylog server

### ISSUE THREAD

**Issue by iscra** [Graylog2/gelf-rb#40]
This client library does not respect chunk limit, so long messages (more than 128 chunks), are not properly encoded and cause Graylog server (current 1.3.3) to crash and stop processing any message.
The whole GELF input is blocks and processing buffer runs full.

Graylog specifies (http://docs.graylog.org/en/latest/pages/gelf.html#chunked-gelf):

Chunked GELF
All chunks MUST arrive within 5 seconds or the server will discard all already arrived and still arriving chunks. A message MUST NOT consist of more than 128 chunks.

**Comment by bernd** [comment]
@iscra Thank you for the report! The gelf-rb code has been fixed as well as the code on the server. (see https://github.com/Graylog2/graylog2-server/pull/1986)
