### ISSUE TITLE
GELF version 1.1?

### ISSUE THREAD

**Issue by mengxi-liao** [Graylog2/gelf-rb#41]
Hi,
from the document http://docs.graylog.org/en/latest/pages/gelf.html we know that the current version should be 1.1. But seems like the gem is only supporting 1.0. Is there any reason why the gem should still use 1.0?

**Comment by joschi** [comment]
The main difference between GELF 1.0 and 1.1 is that GELF 1.0 defined more mandatory fields which have been made optional or marked deprecated in GELF 1.1, so there's no real disadvantage for this library when using GELF 1.0.
